USE [master]
GO

/****** Object:  Database [REBOOT]    Script Date: 13.10.2019 22:54:05 ******/
DROP DATABASE [REBOOT]
GO

/****** Object:  Database [REBOOT]    Script Date: 13.10.2019 22:54:05 ******/
CREATE DATABASE [REBOOT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'REBOOT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\rebootDB.mdb' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'REBOOT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\rebootlog.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [REBOOT] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [REBOOT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [REBOOT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [REBOOT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [REBOOT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [REBOOT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [REBOOT] SET ARITHABORT OFF 
GO

ALTER DATABASE [REBOOT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [REBOOT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [REBOOT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [REBOOT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [REBOOT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [REBOOT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [REBOOT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [REBOOT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [REBOOT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [REBOOT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [REBOOT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [REBOOT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [REBOOT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [REBOOT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [REBOOT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [REBOOT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [REBOOT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [REBOOT] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [REBOOT] SET  MULTI_USER 
GO

ALTER DATABASE [REBOOT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [REBOOT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [REBOOT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [REBOOT] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [REBOOT] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [REBOOT] SET  READ_WRITE 
GO


